default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace # Trims trailing whitespace.
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
      - id: check-added-large-files # Prevent giant files from being committed.
      - id: requirements-txt-fixer
      - id: check-merge-conflict

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.5.3
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        entry: mypy
        files: send/
        language: system
        args: [--install-types, --non-interactive]
